services:
  - type: web
    name: backend
    env: python
    buildCommand: |
      #!/usr/bin/env bash
      pip install -r backend/requirements.txt
      cd backend
      python manage.py migrate
    startCommand: cd backend && gunicorn backend.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: backend-db
          property: connectionString
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings

databases:
  - name: backend-db
    databaseName: backend
    user: backend 