services:
  - type: web
    name: menu-interac
    env: python
    buildCommand: |
      cd backend
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
      python manage.py create_superuser
    startCommand: cd backend && gunicorn backend.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: menu-interac-db
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: menu-interac.onrender.com
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@example.com
      - key: DJANGO_SUPERUSER_PASSWORD
        value: admin123

databases:
  - name: menu-interac-db
    databaseName: menu_interac
    user: menu_interac_user 