# Generated by Django 5.2 on 2025-05-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_alter_plato_precio_detallepedido_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='categoria',
            field=models.CharField(default='sin_categoria', max_length=50),
        ),
        migrations.AlterField(
            model_name='plato',
            name='imagen',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plato',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterModelTable(
            name='plato',
            table='src_plato',
        ),
    ]
